name: Publish npm package to storybook actions test

on:
  release:
    types: [created]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.0
          registry-url: https://npm.pkg.github.com/
          scope: 'action-crey'
      - name: Overwrite main folder 
        run: |
          npm install -g json
          json -I -f package.json -e "this.main='dist/index.js'" -o json -4
          git config --local user.email "${{ github.actor }}-action@github.com"
          git config --local user.name "GitHub Action - ${{ github.actor }}"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Overwrite main folder"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Npm Install
        run: npm i
      - name: Distribution 
        run: npm run dist
      - name: Npm Build & Deploy
          run: npm run storybook:build
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
      - name: Update version ${{ github.event.release.tag_name }}
        run: | 
          git config --local user.email "${{ github.actor }}-action@github.com"
          git config --local user.name "GitHub Action - ${{ github.actor }}"
          npm version ${{ github.event.release.tag_name }} -m "Release ${{ github.event.release.tag_name }} version"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish Release version
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
        if: github.event.release.prerelease == false
      - name: Publish Pre-Release version
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
        if: github.event.release.prerelease == true  
      - name: Push
        uses: github-actions-x/commit@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          commit-message: "Release"
          rebase: 'true' # pull abd rebase before commit: